# -*- coding: utf-8 -*-
"""setup.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AsJAlR7UEcMuAESOhpcSyulSKEUPAG-K
"""

from setuptools import setup, find_packages
from pathlib import Path

this_directory = Path(__file__).parent
long_description = (this_directory / "README.md").read_text()

setup(
    name='topsis-102203846',
    version='1.0.8',
    description='A Python package to calculate TOPSIS scores',
    long_description=long_description,
    long_description_content_type='text/markdown',
    author='Aditi Sinha',
    author_email='adisin0427@gmail.com',
    packages=find_packages(),
    py_modules=['aditi_102203846'],  # Use the new module name
    install_requires=[
        'pandas',
        'numpy',
    ],
    entry_points={
        'console_scripts': [
            'topsis=aditi_102203846:main',  # Update to use the new module and main function
        ],
    },
)